Repository Katello/katello-installer, pull requests merged in 2018-12, with the labels that each got.

#684 Fixes #24947 - Move tar file parameter to the certs module
  README.md
  config/foreman-proxy-content.migrations/180914180308-move-certs-tar-answer.rb
  config/katello.migrations/180914180308-move-certs-tar-answer.rb
  hooks/boot/02-message-helpers.rb
  hooks/pre_validations/12-check_capsule_tar.rb
Labels: Needs testing, Not yet reviewed

#722 Release Katello 3.9.1
  Puppetfile.lock
Labels: Needs testing, Not yet reviewed, Waiting on contributor

#724 Fixes #25625 - Remove old installer redirect scripts
  bin/capsule-installer
  bin/capsule-remove
  bin/katello-installer
Labels: Needs testing, Not yet reviewed

#728 Refs #25662 - Fix rubocop issue in check-disk
  hooks/pre/15-check-disk.rb
Labels: Needs testing, Not yet reviewed

#727 Drop Foreman from Apache group on upgrade
  hooks/pre/30-upgrade.rb
Labels: Needs testing, Not yet reviewed, Waiting on contributor

#729 Fixes #25665 - Use the bash comparisons can function calls
  bin/katello-certs-check
Labels: Ready for merge

#730 Refs #25625 - Remove migration from ancient installers
  hooks/pre_migrations/01-migrate_legacy_foreman_installer_config.rb
  hooks/pre_migrations/10-migrate_legacy_capsule_config.rb
  hooks/pre_migrations/11-migrate_legacy_katello_config.rb
Labels: Needs testing, Not yet reviewed

#725 Fixes #25634 - update db location and sed on removal
  hooks/pre/31-mongo_storage_engine.rb
Labels: Not yet reviewed
