Repository Katello/katello-installer, pull requests merged in 2018-04, with the labels that each got.

#609 Refs #23030 - Add upgrade step for Mongo 3.x
  hooks/post/30-upgrade.rb
  hooks/pre/10-reset_feature.rb
  hooks/pre/30-upgrade.rb
Labels: Needs re-review, Needs testing

#612 Fixes #23242 - Add cli plugins to Katello scenario
  config/katello-answers.yaml
Labels: Needs testing, Not yet reviewed

#613 Fixes #23345 - only call cleanup if we could initialize
  bin/foreman-proxy-certs-generate
Labels: Needs testing, Not yet reviewed

#550 Refs #20550 - Reset remote database
  hooks/boot/01-helpers.rb
  hooks/pre/10-reset_feature.rb
  hooks/pre_commit/05-puppet_certs_exist.rb
Labels: Needs testing

#614 Fixes #23368 - Drop service_wait module
  Puppetfile
  Rakefile
Labels: Needs testing, Not yet reviewed

#615 Fixes #23368 - Drop service_wait module
  Puppetfile
  Rakefile
Labels: Needs testing, Not yet reviewed

#616 Fixes #23407 - remove service-wait
  hooks/pre/10-reset_feature.rb
  hooks/pre/30-upgrade.rb
Labels: Needs testing, Not yet reviewed
