Repository Katello/katello-installer, pull requests merged in 2018-11, with the labels that each got.

#710 Release 3.9.0-rc2
  Puppetfile
  Puppetfile.lock
  VERSION
Labels: Ready for merge

#713 Fixes #25386 - Use the module_enabled? helper
  hooks/post/30-upgrade.rb
Labels: Needs testing, Not yet reviewed

#712 Fixes #25386 - Use the module_enabled? helper
  hooks/post/30-upgrade.rb
Labels: Needs testing, Not yet reviewed

#715 Fixes #25516 - Check LC_ALL is not set to C
  checks/lang.rb
Labels: Needs testing, Not yet reviewed

#719 Fixes #25563 - Remove default_values_dir from configs
  bin/foreman-proxy-certs-generate
  config/foreman-proxy-content.yaml
  config/katello.yaml
Labels: Needs testing, Not yet reviewed, Waiting on contributor

#720 Bump to 3.10.0.rc1
  .gitignore
  Puppetfile
  Puppetfile.lock
  Rakefile
  VERSION
Labels: Needs testing, Not yet reviewed, Waiting on contributor

#721 Bump version to 3.11
  VERSION
Labels: Needs testing, Not yet reviewed, Waiting on contributor
