Repository Katello/katello-installer, pull requests merged in 2018-05, with the labels that each got.

#617 Fixes #23470 - Reset puppet server version to ensure smooth upgrades
  hooks/boot/31-upgrade-puppet.rb
  hooks/init/31-upgrade-puppet.rb
  hooks/post/31-upgrade-puppet.rb
  hooks/pre_validations/31-upgrade-puppet.rb
Labels: Needs testing, Not yet reviewed, Waiting on contributor

#622 Cherry picks for 3.7
  hooks/pre_validations/31-upgrade-puppet.rb
Labels: Needs testing, Not yet reviewed

#624 fixes #23375 - use db names from puppet params
  hooks/pre/10-reset_feature.rb
Labels: Needs testing, Not yet reviewed

#625 Fixes #23564 - enable mongo software collection
  hooks/pre/10-reset_feature.rb
Labels: Needs testing

#607 Refs #23025 escape db connection string
  hooks/pre/30-upgrade.rb
Labels: Needs testing, Not yet reviewed

#626 Fixes #23567 - Remove puppet-common dependency
  Puppetfile
Labels: Needs testing, Not yet reviewed

#631 Fixes #23603 - Correct --upgrade-puppet help text
  hooks/boot/31-upgrade-puppet.rb
Labels: Ready for merge

#630 Fixes #23603 - Correct --upgrade-puppet help text
  hooks/boot/31-upgrade-puppet.rb
Labels: Ready for merge

#629 Refs #23470 - Remove mention of --upgrade-puppet flag
  hooks/pre/30-upgrade.rb
Labels: Ready for merge

#632 Fixes #22598 - add check for key usage Key Encipherment
  bin/katello-certs-check
Labels: Needs testing, Not yet reviewed

#633 Fixes #23649 - remove pulp node pre upgrade steps
  hooks/pre/30-upgrade.rb
Labels: Needs testing, Not yet reviewed

#634 Fixes #23657 - Remove no longer needed steps from upgrade hooks.
  hooks/post/30-upgrade.rb
  hooks/pre/30-upgrade.rb
Labels: Needs testing, Not yet reviewed

#636 Refs #15963 - katello-installer --help typos
  hooks/boot/10-reset_hook.rb
Labels: Needs testing, Not yet reviewed

#635 Cherry picks for 3.6.1
  hooks/pre/21-check-hammer-credentials.rb
Labels: Needs testing, Not yet reviewed

#611 Fixes #23292 - make s390x ks repos bootable
  hooks/post/30-upgrade.rb
Labels: Needs testing, Not yet reviewed

#638 Fixes #23725 - Stop HTTP config mangling
  hooks/pre/30-upgrade.rb
Labels: Needs testing, Not yet reviewed

#641 Pin Puppet modules for 3.7
  .gitignore
  Puppetfile
  Puppetfile.lock
Labels: Needs testing, Not yet reviewed, Waiting on contributor

#640 Fixes #23292 - make s390x ks repos bootable
  hooks/post/30-upgrade.rb
Labels: Needs testing, Not yet reviewed

#642 Bump puppet-qpid to 4.2.1 for rsyslog error
  Puppetfile.lock
Labels: Needs testing, Not yet reviewed, Waiting on contributor
