Repository Katello/katello-installer, pull requests merged in 2018-10, with the labels that each got.

#694 Refs #24966 - Move mongo syspath to after upgrade
  hooks/post/31-mongo_syspath.rb
  hooks/post/9-mongo_syspath.rb
Labels: Ready for merge

#697 [CP] Missed 3.7.1 pick
  config/foreman-proxy-content.migrations/180829115142_change_rex_ssh_dir.rb
  config/katello.migrations/180829115142_change_rex_ssh_dir.rb
Labels: Needs testing, Not yet reviewed, Waiting on contributor

#698 Refs #12386 - Let qdrouterd listen on IPv6
  config/foreman-proxy-content.migrations/181012141418-qdrouterd-listen-ipv6.rb
  config/katello.migrations/181012141418-qdrouterd-listen-ipv6.rb
Labels: Needs testing, Not yet reviewed

#704 Release RC1.1
  Puppetfile.lock
  VERSION
Labels: Needs testing, Not yet reviewed, Waiting on contributor

#705 set prerelease in version string
  VERSION
Labels: Needs re-review, Needs testing, Waiting on contributor

#706 Fixes #25306 - Add space after command output in kcc
  bin/katello-certs-check
Labels: Not yet reviewed

#707 Fixes #25336 - Move remove MongoDB from post to pre hook.
  hooks/post/30-upgrade.rb
  hooks/pre/30-upgrade.rb
Labels: Not yet reviewed

#708 Fixes #23620 - Fix reset for local & remote MongoDB.
  hooks/pre/10-reset_feature.rb
Labels: Not yet reviewed
