Repository Katello/katello-installer, pull requests merged in 2018-09, with the labels that each got.

#681 Fixes #24815 - Update SAN check to warning and clean up script.
  bin/katello-certs-check
Labels: Needs testing, Not yet reviewed

#657 Fixes #24189 - switch to foreman upgrade task
  hooks/post/30-upgrade.rb
Labels: Needs testing, Not yet reviewed

#683 No need to remove MongoDB log files
  hooks/post/30-upgrade.rb
Labels: Needs testing, Not yet reviewed, Waiting on contributor

#678 Fixes #24752 - reset server_puppetserver_metrics
  hooks/pre_validations/31-upgrade-puppet.rb
Labels: Needs testing, Not yet reviewed

#639 Fixes #24066 - Add Mongo storage engine upgrade
  hooks/boot/21-mongo_storage_engine.rb
  hooks/post/30-upgrade.rb
  hooks/pre/31-mongo_storage_engine.rb
  hooks/pre_validations/30-mongo_storage_engine.rb
Labels: Ready for merge

#685 Fixes #24966 - Move mongo upgrade inside upgrade if logic.
  hooks/post/30-upgrade.rb
Labels: Ready for merge

#682 Refs #24730: add upgrade step clear_checksum_type
  hooks/post/30-upgrade.rb
Labels: Needs testing, Not yet reviewed

#688 Fixes #25011 - only start PostgreSQL in the Katello scenario
  hooks/pre/30-upgrade.rb
Labels: Needs testing, Not yet reviewed

#691 Fixes #25056 - Remove mappings
  config/foreman-proxy-content.migrations/160120212700-foreman-proxy.rb
  config/foreman-proxy-content.migrations/160919172842_infoblox.rb
  config/foreman-proxy-content.migrations/161004173201_smart_proxy_ansible.rb
  config/katello.migrations/160120212701-foreman-proxy.rb
  config/katello.migrations/160919172842_infoblox.rb
  config/katello.migrations/161004173201_foreman_ansible.rb
Labels: Needs testing, Not yet reviewed

#693 Fixes #25061 - Remove EL6 compat in reset_candlepin
  hooks/pre/10-reset_feature.rb
Labels: Needs testing, Not yet reviewed
