Repository Katello/katello-installer, pull requests merged in 2018-02, with the labels that each got.

#585 Remove old puppet hook on Ruby 1.8.7
  hooks/init/10-puppet-profile-on-el6.rb
Labels: Needs testing, Not yet reviewed

#589 Fixes #22558 - Add post install devel instructions
  hooks/boot/02-message-helpers.rb
  hooks/post/10-post_install.rb
Labels: Needs testing, Not yet reviewed

#578 Refs #21703 - remove registration tasks
  hooks/post/30-upgrade.rb
Labels: Needs testing, Not yet reviewed

#588 Update puppet modules for 3.5.1
  Puppetfile
  Puppetfile.lock
  README.md
  Rakefile
  config/katello-devel-answers.yaml
  config/katello-devel.migrations/160120212701-foreman-proxy.rb
  config/katello-devel.migrations/160314145015-qpid-localhost.rb
  config/katello-devel.migrations/160503102719-gutterball.rb
  config/katello-devel.migrations/160601202256-additional-foreman-proxy.rb
  config/katello-devel.migrations/160608111430-additional-foreman-proxy.rb
  config/katello-devel.migrations/160613152647-hiera-config.rb
  config/katello-devel.migrations/160824145544-parser_cache.rb
  config/katello-devel.migrations/160831180000-foreman_proxy_tftp_grub2.rb
  config/katello-devel.migrations/161121212031-move_capsule_to_foreman_proxy_content.rb
  config/katello-devel.migrations/161124183732-remove-mappings.rb
  config/katello-devel.migrations/161216113043-move_puppet_to_top_level.rb
  config/katello-devel.migrations/170109180612-dhcp_range_cant_be_false.rb
  config/katello-devel.migrations/180111142132-foreman_proxy_autosignfile.rb
  config/katello-devel.migrations/20160301144353-order.rb
  config/katello-devel.migrations/20161123223115_order.rb
  config/katello-devel.yaml
  spec/migration_spec.rb
Labels: Needs testing, Not yet reviewed, Waiting on contributor

#590 Bump to 3.5.1.1
  VERSION
Labels: Needs testing, Not yet reviewed, Waiting on contributor

#592 Fixes #22608 - add req to required opts
  bin/katello-certs-check
Labels: Needs testing, Not yet reviewed

#591 Fixes #22598 - add san check
  bin/katello-certs-check
Labels: Needs re-review, Needs testing

#593 Fixes #22173 - Rework Reverse DNS error
  checks/dns.rb
Labels: Needs re-review, Needs testing, Waiting on contributor

#594 Fixes #22694 - added check on cert hostname output
  bin/katello-certs-check
Labels: Needs testing, Not yet reviewed
